# Generated by Django 3.0.8 on 2020-07-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='country',
            field=models.CharField(choices=[('SR', 'Suriname'), ('US', 'UnitedStates')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
    ]
