# Generated by Django 3.0.8 on 2020-08-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20200728_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='send_gap',
        ),
    ]
