# Generated by Django 3.0.8 on 2020-08-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_remove_subscribe_send_gap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
